services:
  shush-design:
    build: .
    ports:
      - "5036:8080"
    environment:
      Credentials__Username: ${SHUSH_USERNAME}
      Credentials__Password: ${SHUSH_PASSWORD}
    volumes:
      - shush-data:/app/.shush

volumes:
  shush-data:
